categorical:

- monthly_3g_6
- monthly_2g_7
- monthly_2g_8
- sachet_2g_6

- sachet_3g_7
- monthly_3g_8
- monthly_2g_6
- sachet_3g_8
- sachet_3g_6
- monthly_3g_7
- date_of_last_rech_6
- date_of_last_rech_7
- date_of_last_rech_8
date_columns:
- date_of_last_rech_6
- date_of_last_rech_7
- date_of_last_rech_8
- date_of_last_rech_data_6
- date_of_last_rech_data_7
- date_of_last_rech_data_8
drop:
- circle_id
- loc_og_t2o_mou
- std_og_t2o_mou
- loc_ic_t2o_mou
- last_date_of_month_6
- last_date_of_month_7
- last_date_of_month_8

- std_og_t2c_mou_6
- std_og_t2c_mou_7
- std_og_t2c_mou_8

- std_ic_t2o_mou_6
- std_ic_t2o_mou_7
- std_ic_t2o_mou_8

- date_of_last_rech_data_6
- date_of_last_rech_data_7
- date_of_last_rech_data_8

- max_rech_data_6
- max_rech_data_7
- max_rech_data_8

- count_rech_2g_6
- count_rech_2g_7
- count_rech_2g_8

- count_rech_3g_6
- count_rech_3g_7
- count_rech_3g_8

- arpu_3g_6
- arpu_3g_7
- arpu_3g_8

- arpu_2g_6
- arpu_2g_7
- arpu_2g_8

- night_pck_user_6
- night_pck_user_7
- night_pck_user_8

- fb_user_6
- fb_user_7
- fb_user_8

- total_rech_data_amt_6
- total_rech_data_amt_7
- total_rech_data_amt_8

- mobile_number
dropChurnPhaseColumns:
- std_ic_t2o_mou_9
- date_of_last_rech_data_9
- max_rech_data_9
- count_rech_2g_9
- last_date_of_month_9
- std_og_t2c_mou_9
- total_rech_data_amt_9
- count_rech_3g_9
- fb_user_9
- arpu_2g_9
- night_pck_user_9
- arpu_3g_9
- arpu_9
- onnet_mou_9
- offnet_mou_9
- roam_ic_mou_9
- std_og_t2c_mou_9
- roam_og_mou_9
- last_date_of_month_9
- std_ic_t2o_mou_9
- loc_og_t2t_mou_9
- loc_og_t2m_mou_9
- loc_og_t2f_mou_9
- loc_og_t2c_mou_9
- loc_og_mou_9
- std_og_t2t_mou_9
- std_og_t2m_mou_9
- std_og_t2f_mou_9
- std_og_mou_9
- isd_og_mou_9
- spl_og_mou_9
- og_others_9
- total_og_mou_9
- loc_ic_t2t_mou_9
- loc_ic_t2m_mou_9
- loc_ic_t2f_mou_9
- loc_ic_mou_9
- std_ic_t2t_mou_9
- std_ic_t2m_mou_9
- std_ic_t2f_mou_9
- std_ic_mou_9
- total_ic_mou_9
- spl_ic_mou_9
- isd_ic_mou_9
- ic_others_9
- total_rech_num_9
- total_rech_amt_9
- max_rech_amt_9
- date_of_last_rech_9
- last_day_rch_amt_9
- vol_2g_mb_9
- vol_3g_mb_9
- monthly_2g_9
- sachet_2g_9
- monthly_3g_9
- sachet_3g_9
- sep_vbc_3g
nullFillMode:
- date_of_last_rech_6
- date_of_last_rech_7
- date_of_last_rech_8
nullFillZero:
- onnet_mou_6
- offnet_mou_6
- roam_ic_mou_6
- roam_og_mou_6
- loc_og_t2t_mou_6
- loc_og_t2m_mou_6
- loc_og_t2f_mou_6
- loc_og_t2c_mou_6
- loc_og_mou_6
- std_og_t2t_mou_6
- std_og_t2m_mou_6
- std_og_t2f_mou_6
- std_og_mou_6
- isd_og_mou_6
- spl_og_mou_6
- og_others_6
- loc_ic_t2t_mou_6
- loc_ic_t2m_mou_6
- loc_ic_t2f_mou_6
- loc_ic_mou_6
- std_ic_t2t_mou_6
- std_ic_t2m_mou_6
- std_ic_t2f_mou_6
- std_ic_mou_6
- spl_ic_mou_6
- isd_ic_mou_6
- ic_others_6
- onnet_mou_7
- offnet_mou_7
- roam_ic_mou_7
- roam_og_mou_7
- loc_og_t2t_mou_7
- loc_og_t2m_mou_7
- loc_og_t2f_mou_7
- loc_og_t2c_mou_7
- loc_og_mou_7
- std_og_t2t_mou_7
- std_og_t2m_mou_7
- std_og_t2f_mou_7
- std_og_mou_7
- isd_og_mou_7
- spl_og_mou_7
- og_others_7
- loc_ic_t2t_mou_7
- loc_ic_t2m_mou_7
- loc_ic_t2f_mou_7
- loc_ic_mou_7
- std_ic_t2t_mou_7
- std_ic_t2m_mou_7
- std_ic_t2f_mou_7
- std_ic_mou_7
- spl_ic_mou_7
- isd_ic_mou_7
- ic_others_7
- onnet_mou_8
- offnet_mou_8
- roam_ic_mou_8
- roam_og_mou_8
- loc_og_t2t_mou_8
- loc_og_t2m_mou_8
- loc_og_t2f_mou_8
- loc_og_t2c_mou_8
- loc_og_mou_8
- std_og_t2t_mou_8
- std_og_t2m_mou_8
- std_og_t2f_mou_8
- std_og_mou_8
- isd_og_mou_8
- spl_og_mou_8
- og_others_8
- loc_ic_t2t_mou_8
- loc_ic_t2m_mou_8
- loc_ic_t2f_mou_8
- loc_ic_mou_8
- std_ic_t2t_mou_8
- std_ic_t2m_mou_8
- std_ic_t2f_mou_8
- std_ic_mou_8
- spl_ic_mou_8
- isd_ic_mou_8
- ic_others_8
rename:
  aug_vbc_3g: vbc_3g_8
  jul_vbc_3g: vbc_3g_7
  jun_vbc_3g: vbc_3g_6
